---
plan: free
capacity: 100
local_db: sqlite3:/var/vcap/services/couchdb/couchdb_node.db
mbus: nats://localhost:4222
base_dir: /var/vcap/services/couchdb/
index: 0
logging:
  level: debug
pid: /var/vcap/sys/run/couchdb_node.pid
node_id: couchdb_node_1
supported_versions: ["1.0"]
default_version: "1.0"
couchdb_admin: admin
